export default interface IAssessmentData {
  id?: string;
  date: string;
  time: string;
  expert: string;
  name: string;
  email: string;
  phone: string;
  call_picked: string;
  age: string;
  gender: string;
  country: string;
  state: string;
  city: string;
  nationality: string;
  languages: string[];
  educational_qualification: string;
  relationship_status: string;
  dependents: string;
  student: string;
  occupation: string;
  occupation_type: string;
  family_mental_history: string;
  symptoms: string;
  frequency_of_symptoms: string;
  medication_history: string;
  therapeutic_histroy: string;
  types_of_theraputic_history: string[];
  urgency_of_intervention: string;
  gender_of_therapist: string;
  age_group_of_therapist: string;
  therapy_delivery_modes: string[];
  therapy_type: string[];
  preferred_language: string;
  expert_suggested: string;
  suggested_expert_name1: string,
  suggested_expert_name2: string,
  suggested_expert_name3: string,
  suggest_therapy_type: string;
  notes: string;
  issues: string[];
  reason_for_interest: string;
  length_of_concern: string;
  current_physical_fitness: string;
  exercise_routine: string;
  health_problems: string;
  physical_pain: string;
  physical_pain_description: string;
  budget: string;
  lead_owner: string;
  lead_status: string;
}
